#! /usr/bin/gawk -f

# --------------------------------------------------------------------------
# Auxiliary script for regression testing environment
#
# Modify Intel® 8 HEX files generated by assembler, file extension is `.hex'
# --------------------------------------------------------------------------


# Just copy input to output
{
	print($0)
}
